### ISSUE TITLE
[TODO] Rename to essence-archive-viewer

### ISSUE THREAD

**Issue by Janne252** [Janne252/essence-archive-viewer#1]
- [ ] ~~create a new repository `essence-archive-viewer`~~ [GitHub handles redirects automatically](https://github.blog/2013-05-16-repository-redirects-are-here/)
    - [x] Rename app to Essence Archive Viewer 
    - [x] move main title bar credit text to about window
    - [x] add a link to the new repository to the about window
    - [x] upload a new release
    - [x] readme: list CoH2, CoH3, and AoE4 as supported games (essence engine version ? - 5) 
- [ ] ~~update readme on this project to point to the new repository~~
- [ ] ~~archive this project~~
- [ ] update blog posts to link to the new repository

**Comment by mbwilding** [comment]
Forked.

**Comment by Janne252** [comment]
> Forked.

Hey, I intended this issue as a personal TODO since the scope of the tool has expanded to at least two Essence Engine 5.0 based games. Apologies for misleading title.

**Comment by mbwilding** [comment]
No worries, hopefully it's fine that I forked it, I closed the pull request.
